---

- name: Initialize control plane
  become: true
  ansible.builtin.command: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Get worker join command
  become: true
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command
  changed_when: false

- name: Set worker join command fact
  ansible.builtin.set_fact:
    worker_join_cmd: "{{ join_command.stdout }}"
