---

- name: Load kernel module
  become: true
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - overlay
    - br_netfilter

- name: Enable bridge network and ipv4 forwarding
  become: true
  ansible.builtin.copy:
    src: etc/sysctl.d/k8s.conf
    dest: /etc/sysctl.d/
    owner: root
    group: root
    mode: '0644'

- name: Apply sysctl settings
  become: true
  ansible.builtin.reboot:
